#!/usr/bin/env python3
"""Exploratory: decode EVERY JSR/JMP-target subroutine in all three Lunar
Lander vector ROMs into one JS module (discovery_rom_data.js) so demos/gallery
can render the whole ROM contents for visual identification.

This is a survey tool, NOT the curated runtime data (that's build_vector_rom.py).
Subroutines are named `S_<cpuaddr>`; terrain polyline entry points (from the
034597 pointer table) are named `T_<cpuaddr>`. Reuses decode_opcode/format_op
from build_vector_rom.py (same dir).
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_vector_rom import decode_opcode, format_op  # noqa: E402

ROM_DIRS = [Path("C:/Z_Temp/lunar_lander"), Path("D:/tmp/lunar_lander")]
OUT = Path(__file__).resolve().parents[1] / "discovery_rom_data.js"

# (js-var, filename, cpu base)
ROMS = [
    ("ROM599", "034599-01.r3", 0x4800),
    ("ROM598", "034598-01.np3", 0x5000),
    ("ROM597", "034597-01.m3", 0x5800),
]


def load(name: str) -> bytes:
    for d in ROM_DIRS:
        if (d / name).exists():
            return (d / name).read_bytes()
    raise SystemExit(f"{name} not found in {ROM_DIRS}")


def word(b: bytes, o: int) -> int:
    return b[o] | (b[o + 1] << 8)


def decode_tolerant(b: bytes, base: int, start_cpu: int) -> list[dict]:
    """Walk from start_cpu until RTS or HALT (tolerant — no exceptions)."""
    ops: list[dict] = []
    pc = start_cpu - base
    while pc + 2 <= len(b):
        op = (word(b, pc) >> 12) & 0xF
        width = 4 if op <= 0xA else 2
        if pc + width > len(b):
            break
        oc = decode_opcode(base + pc, list(b[pc:pc + width]))
        ops.append(oc)
        pc += width
        if oc["op"] in ("RTS", "HALT"):
            break
    # resolve JSR/JMP targets to S_<cpu> names
    for oc in ops:
        if "_target_word" in oc:
            cpu = oc["_target_word"] * 2 + 0x4000
            oc["target"] = f"S_{cpu:04X}"
            del oc["_target_word"]
    return ops


def jsr_targets(b: bytes, base: int) -> list[int]:
    """Walk the instruction stream from offset 0, collect in-range JSR/JMP targets."""
    targets: set[int] = set()
    pc = 0
    while pc + 2 <= len(b):
        w = word(b, pc)
        op = (w >> 12) & 0xF
        if op in (0xC, 0xE):
            cpu = (w & 0xFFF) * 2 + 0x4000
            if base <= cpu < base + len(b):
                targets.add(cpu)
        pc += 4 if op <= 0xA else 2
    return sorted(targets)


def terrain_pointers(b: bytes, base: int) -> list[int]:
    """034597: raw address-word table starting at offset 4 (after the 0x3000/0x0060
    header), taken while words stay inside the ROM range."""
    ptrs: list[int] = []
    o = 4
    while o + 2 <= len(b):
        v = word(b, o)
        if base <= v < base + len(b):
            ptrs.append(v)
            o += 2
        else:
            break
    return ptrs


def emit() -> str:
    lines = [
        "// lunar_lander/discovery_rom_data.js",
        "// GENERATED by tools/build_discovery.py — EXPLORATORY ROM survey, not curated.",
        "// Every JSR/JMP-target subroutine in each ROM, named S_<cpuaddr>; 034597",
        "// terrain polyline entry points named T_<cpuaddr>. For demos/gallery.html.",
        "",
    ]
    for var, fname, base in ROMS:
        b = load(fname)
        subs: dict[str, list[dict]] = {}
        for a in jsr_targets(b, base):
            subs[f"S_{a:04X}"] = decode_tolerant(b, base, a)
        if var == "ROM597":
            for a in terrain_pointers(b, base):
                subs[f"T_{a:04X}"] = decode_tolerant(b, base, a)
        lines.append(f"// ----- {fname} (CPU ${base:04X}-${base+len(b)-1:04X}) — {len(subs)} subs -----")
        lines.append(f"export const {var} = {{")
        for name, ops in subs.items():
            lines.append(f"  {name}: [{', '.join(format_op(o) for o in ops)}],")
        lines.append("};")
        lines.append("")
        print(f"{fname}: {len(subs)} subs")
    return "\n".join(lines)


if __name__ == "__main__":
    OUT.write_text(emit(), encoding="utf-8")
    print(f"wrote: {OUT}")
