#!/usr/bin/env python3
"""
extract_frametable.py -- extract SDLPoP's frame_table_kid[] into a JS data module.

frame_table_kid (seg006.c, "data:0FE0") maps a frame number (Char.frame) to
{ image, sword, dx, dy, flags } (frame_type, types.h:361). We need it to draw an
animation frame: `image` picks the sprite (kid body image N -> KID.DAT resource
401+N), and dx/dy are the per-frame draw-registration offsets used by
load_frame_to_obj (seg008.c:1736):
    obj_x = (char_dx_forward(cur_frame.dx) << 1) - 116
    obj_y = cur_frame.dy + Char.y

Ported from SDLPoP (GPLv3) -- see the project NOTICE.

Usage:  python extract_frametable.py <path/to/SDLPoP/src/seg006.c> [out.js]
"""
import re, sys, os

def val(s):
    s = s.strip()
    if '|' in s:                       # e.g. "0xC0| 4"  ->  0xC0 | 4
        a, b = s.split('|')
        return int(a, 0) | int(b, 0)
    return int(s, 0)                   # handles decimal, hex, and negatives

def main():
    if len(sys.argv) < 2:
        print("usage: python extract_frametable.py <seg006.c> [out.js]"); return
    src = open(sys.argv[1], encoding="utf-8", errors="replace").read()
    out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(__file__), "..", "res", "frame_table_kid.js")
    out_path = os.path.abspath(out_path)

    m = re.search(r'const frame_type frame_table_kid\[\]\s*=\s*\{(.*?)\n\};', src, re.S)
    if not m:
        print("frame_table_kid[] not found"); return
    rows = []
    for entry in re.findall(r'\{([^{}]*)\}', m.group(1)):
        f = entry.split(',')
        if len(f) != 5:
            continue
        rows.append([val(f[0]), val(f[1]), val(f[2]), val(f[3]), val(f[4])])

    lines = [
        "// GENERATED by tools/extract_frametable.py from SDLPoP seg006.c frame_table_kid[].",
        "// One row per frame number (Char.frame indexes this): [image, sword, dx, dy, flags].",
        "//   image 255 = blank; kid body image N -> KID.DAT resource 401+N.",
        "//   dx,dy = draw-registration offsets (load_frame_to_obj, seg008.c:1736).",
        "// Ported from SDLPoP (GPLv3) -- see NOTICE.",
        "export const FRAME_TABLE_KID = [",
    ]
    lines += [f"  [{r[0]}, {r[1]}, {r[2]}, {r[3]}, {r[4]}]," for r in rows]
    lines += ["];", ""]
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fp:
        fp.write("\n".join(lines))

    print(f"frames parsed : {len(rows)}  (frame 0..{len(rows)-1})")
    print(f"wrote         : {out_path}")

if __name__ == "__main__":
    main()
