#!/usr/bin/env python3
# Reads the Phoenix tile + palette ROMs from the disassembly clone and emits
# phoenix_clone/data.js with three Uint8Array byte literals.
#
# Run from anywhere:
#     python phoenix_clone/tools/build_data.py
#
# Source ROMs:
#     D:/tmp/computer_archeology_phonenix/content/Arcade/Phoenix/roms/
#         fgtiles.bin   (4096 bytes — ic39 + ic40 concatenated, 1 bitplane each)
#         bgtiles.bin   (4096 bytes — ic23 + ic24 concatenated, 1 bitplane each)
#         proms.bin     ( 512 bytes — ic40 + ic41 concatenated, 1 palette bit each)

from pathlib import Path

ROM_DIR  = Path("D:/tmp/computer_archeology_phonenix/content/Arcade/Phoenix/roms")
OUT_FILE = Path(__file__).resolve().parent.parent / "data.js"

ROMS = [
    ("fgtilesData", "fgtiles.bin", 4096),
    ("bgtilesData", "bgtiles.bin", 4096),
    ("promsData",   "proms.bin",    512),
]


def read_rom(name: str, expected: int) -> bytes:
    path = ROM_DIR / name
    data = path.read_bytes()
    if len(data) != expected:
        raise SystemExit(f"{path}: expected {expected} bytes, got {len(data)}")
    return data


def format_bytes(data: bytes, indent: str = "    ", per_row: int = 16) -> str:
    lines = []
    for row_start in range(0, len(data), per_row):
        row = data[row_start:row_start + per_row]
        lines.append(indent + ", ".join(f"0x{b:02X}" for b in row) + ",")
    return "\n".join(lines)


def main() -> None:
    blocks = [read_rom(name, size) for (_, name, size) in ROMS]

    out = []
    out.append("// data.js — auto-generated by phoenix_clone/tools/build_data.py")
    out.append("// Source: D:/tmp/computer_archeology_phonenix/content/Arcade/Phoenix/roms/")
    out.append("// Do not edit by hand; re-run the prep script if the ROMs change.")
    out.append("")

    for (var_name, _, _), data in zip(ROMS, blocks):
        out.append(f"export const {var_name} = new Uint8Array([")
        out.append(format_bytes(data))
        out.append("]);")
        out.append("")

    OUT_FILE.write_text("\n".join(out), encoding="utf-8")
    total = sum(len(b) for b in blocks)
    print(f"wrote {OUT_FILE}  ({total} bytes of ROM data, {OUT_FILE.stat().st_size} bytes of JS)")


if __name__ == "__main__":
    main()
