#!/usr/bin/env python3
# Reads the Phoenix ROMs from the disassembly clone and emits
# phoenix_clone/data.js with the tile/palette byte arrays plus parsed
# static-text-table records (PrintTextLines $01D0 input data).
#
# Run from anywhere:
#     python phoenix_clone/tools/build_data.py
#
# Source ROMs:
#     D:/tmp/computer_archeology_phonenix/content/Arcade/Phoenix/roms/
#         fgtiles.bin   (4096 bytes — ic39 + ic40 concatenated, 1 bitplane each)
#         bgtiles.bin   (4096 bytes — ic23 + ic24 concatenated, 1 bitplane each)
#         proms.bin     ( 512 bytes — ic40 + ic41 concatenated, 1 palette bit each)
#         maincpu.bin   (16384 bytes — ic45+ic46+ic47+ic48+h5..h8 concatenated)

from pathlib import Path

ROM_DIR  = Path("D:/tmp/computer_archeology_phonenix/content/Arcade/Phoenix/roms")
OUT_FILE = Path(__file__).resolve().parent.parent / "data.js"

ROMS = [
    ("fgtilesData", "fgtiles.bin", 4096),
    ("bgtilesData", "bgtiles.bin", 4096),
    ("promsData",   "proms.bin",    512),
]

MAINCPU_NAME = "maincpu.bin"
MAINCPU_SIZE = 16384

# Static-text tables consumed by PrintTextLines ($01D0). Format per entry
# (32 bytes in the code ROM):
#   +0..+1   screen-RAM address (MSB, LSB)
#   +2..+5   four FF padding bytes (skipped via L+=5)
#   +6..+31  26 tile bytes (one per display column, drawn left-to-right)
# The address inverse (addr → x, y) is described in
# phoenix_clone/docs/research_rendering.md §4.3 "Static text tables".
#
# Known $01D0 call sites in Code.md (add to TEXT_TABLES as the port grows):
#     $0017 (cold-init):           T1800, 3 rows  ← extracted here
#     $01E1 (PrintCopyright):      T1960, 3 rows
#     $0290 (PromptForStartGame):  T19C0, 2 rows
#     $02A2 (PromptForStartGame):  T1BA0, 1 row
#     $06ED:                       T1800, 1 row (reuses first T1800 entry)
TEXT_TABLES = [
    ("T1800", 0x1800, 3),
]


def read_rom(name: str, expected: int) -> bytes:
    path = ROM_DIR / name
    data = path.read_bytes()
    if len(data) != expected:
        raise SystemExit(f"{path}: expected {expected} bytes, got {len(data)}")
    return data


def format_bytes(data: bytes, indent: str = "    ", per_row: int = 16) -> str:
    lines = []
    for row_start in range(0, len(data), per_row):
        row = data[row_start:row_start + per_row]
        lines.append(indent + ", ".join(f"0x{b:02X}" for b in row) + ",")
    return "\n".join(lines)


def parse_text_table(rom: bytes, offset: int, row_count: int) -> list[dict]:
    records = []
    for i in range(row_count):
        base = offset + i * 32
        addr = (rom[base] << 8) | rom[base + 1]
        # addr → (col, row) → (x, y); see research_rendering.md §4.3.
        plane_off = addr - 0x4000
        col = 25 - (plane_off >> 5)
        row = plane_off & 0x1F
        records.append({
            "x": col * 8,
            "y": row * 8,
            "tiles": list(rom[base + 6 : base + 32]),
        })
    return records


def format_text_table(records: list[dict], indent: str = "    ") -> str:
    lines = []
    for r in records:
        tile_str = ", ".join(f"0x{b:02X}" for b in r["tiles"])
        lines.append(f"{indent}{{ x: {r['x']:3d}, y: {r['y']:3d}, tiles: [{tile_str}] }},")
    return "\n".join(lines)


def main() -> None:
    rom_blocks = [read_rom(name, size) for (_, name, size) in ROMS]
    maincpu = read_rom(MAINCPU_NAME, MAINCPU_SIZE)

    out = []
    out.append("// data.js — auto-generated by phoenix_clone/tools/build_data.py")
    out.append("// Source: D:/tmp/computer_archeology_phonenix/content/Arcade/Phoenix/roms/")
    out.append("// Do not edit by hand; re-run the prep script if the ROMs change.")
    out.append("")

    for (var_name, _, _), data in zip(ROMS, rom_blocks):
        out.append(f"export const {var_name} = new Uint8Array([")
        out.append(format_bytes(data))
        out.append("]);")
        out.append("")

    for name, offset, row_count in TEXT_TABLES:
        records = parse_text_table(maincpu, offset, row_count)
        out.append(f"// {name} — code-ROM offset 0x{offset:04X}, {row_count} row(s).")
        out.append(f"export const {name} = [")
        out.append(format_text_table(records))
        out.append("];")
        out.append("")

    OUT_FILE.write_text("\n".join(out), encoding="utf-8")
    total = sum(len(b) for b in rom_blocks)
    print(f"wrote {OUT_FILE}  ({total} bytes of ROM data, {OUT_FILE.stat().st_size} bytes of JS)")


if __name__ == "__main__":
    main()
