// asteroids_clone/packed_messages.js
// Generated by tools/build_packed_messages.py. DO NOT edit by hand.
// Source: <sparse-clone>/content/Arcade/Asteroids/VectorROM.md ($171E-$17B8)
// Build:  python asteroids_clone/tools/build_packed_messages.py
// Spec:   asteroids_clone/docs/research_game_state_machine.md §7
//
// 11 packed messages from the cabinet's vector ROM, pre-decoded into
// glyph-name arrays. Each entry also carries the LABS coord (DVG-X/4,
// DVG-Y/4) from Code.md's per-msg coord table at $7871. Global scale
// for all packed messages is $10 per $77F6's STA $00 at $77FD-$77FF.

export const PACKED_MSG = {
  // msg-id 0: "HIGH_SCORES" — LABS (100, 182) ×4 = DVG (400, 728)
  HIGH_SCORES: {
    labs: { x: 0x64, y: 0xB6 },
    glyphs: ['Char_H', 'Char_I', 'Char_G', 'Char_H', 'Char_Space', 'Char_S', 'Char_C', 'Char_O', 'Char_R', 'Char_E', 'Char_S'],
  },
  // msg-id 1: "PLAYER_" — LABS (100, 182) ×4 = DVG (400, 728)
  PLAYER: {
    labs: { x: 0x64, y: 0xB6 },
    glyphs: ['Char_P', 'Char_L', 'Char_A', 'Char_Y', 'Char_E', 'Char_R', 'Char_Space'],
  },
  // msg-id 2: "YOUR_SCORE_IS_ONE_OF_THE_TEN_BEST" — LABS (12, 170) ×4 = DVG (48, 680)
  YOUR_SCORE_IS_ONE_OF_THE_TEN_BEST: {
    labs: { x: 0x0C, y: 0xAA },
    glyphs: ['Char_Y', 'Char_O', 'Char_U', 'Char_R', 'Char_Space', 'Char_S', 'Char_C', 'Char_O', 'Char_R', 'Char_E', 'Char_Space', 'Char_I', 'Char_S', 'Char_Space', 'Char_O', 'Char_N', 'Char_E', 'Char_Space', 'Char_O', 'Char_F', 'Char_Space', 'Char_T', 'Char_H', 'Char_E', 'Char_Space', 'Char_T', 'Char_E', 'Char_N', 'Char_Space', 'Char_B', 'Char_E', 'Char_S', 'Char_T'],
  },
  // msg-id 3: "PLEASE_ENTER_YOUR_INITIALS" — LABS (12, 162) ×4 = DVG (48, 648)
  PLEASE_ENTER_YOUR_INITIALS: {
    labs: { x: 0x0C, y: 0xA2 },
    glyphs: ['Char_P', 'Char_L', 'Char_E', 'Char_A', 'Char_S', 'Char_E', 'Char_Space', 'Char_E', 'Char_N', 'Char_T', 'Char_E', 'Char_R', 'Char_Space', 'Char_Y', 'Char_O', 'Char_U', 'Char_R', 'Char_Space', 'Char_I', 'Char_N', 'Char_I', 'Char_T', 'Char_I', 'Char_A', 'Char_L', 'Char_S'],
  },
  // msg-id 4: "PUSH_ROTATE_TO_SELECT_LETTER" — LABS (12, 154) ×4 = DVG (48, 616)
  PUSH_ROTATE_TO_SELECT_LETTER: {
    labs: { x: 0x0C, y: 0x9A },
    glyphs: ['Char_P', 'Char_U', 'Char_S', 'Char_H', 'Char_Space', 'Char_R', 'Char_O', 'Char_T', 'Char_A', 'Char_T', 'Char_E', 'Char_Space', 'Char_T', 'Char_O', 'Char_Space', 'Char_S', 'Char_E', 'Char_L', 'Char_E', 'Char_C', 'Char_T', 'Char_Space', 'Char_L', 'Char_E', 'Char_T', 'Char_T', 'Char_E', 'Char_R'],
  },
  // msg-id 5: "PUSH_HYPERSPACE_WHEN_LETTER_IS_CORRECT" — LABS (12, 146) ×4 = DVG (48, 584)
  PUSH_HYPERSPACE_WHEN_LETTER_IS_CORRECT: {
    labs: { x: 0x0C, y: 0x92 },
    glyphs: ['Char_P', 'Char_U', 'Char_S', 'Char_H', 'Char_Space', 'Char_H', 'Char_Y', 'Char_P', 'Char_E', 'Char_R', 'Char_S', 'Char_P', 'Char_A', 'Char_C', 'Char_E', 'Char_Space', 'Char_W', 'Char_H', 'Char_E', 'Char_N', 'Char_Space', 'Char_L', 'Char_E', 'Char_T', 'Char_T', 'Char_E', 'Char_R', 'Char_Space', 'Char_I', 'Char_S', 'Char_Space', 'Char_C', 'Char_O', 'Char_R', 'Char_R', 'Char_E', 'Char_C', 'Char_T'],
  },
  // msg-id 6: "PUSH_START" — LABS (100, 198) ×4 = DVG (400, 792)
  PUSH_START: {
    labs: { x: 0x64, y: 0xC6 },
    glyphs: ['Char_P', 'Char_U', 'Char_S', 'Char_H', 'Char_Space', 'Char_S', 'Char_T', 'Char_A', 'Char_R', 'Char_T'],
  },
  // msg-id 7: "GAME_OVER" — LABS (100, 157) ×4 = DVG (400, 628)
  GAME_OVER: {
    labs: { x: 0x64, y: 0x9D },
    glyphs: ['Char_G', 'Char_A', 'Char_M', 'Char_E', 'Char_Space', 'Char_O', 'Char_V', 'Char_E', 'Char_R'],
  },
  // msg-id 8: "1_COIN_2_PLAYS" — LABS (80, 57) ×4 = DVG (320, 228)
  ONE_COIN_TWO_PLAYS: {
    labs: { x: 0x50, y: 0x39 },
    glyphs: ['Char_1', 'Char_Space', 'Char_C', 'Char_O', 'Char_I', 'Char_N', 'Char_Space', 'Char_2', 'Char_Space', 'Char_P', 'Char_L', 'Char_A', 'Char_Y', 'Char_S'],
  },
  // msg-id 9: "1_COIN_1_PLAY" — LABS (80, 57) ×4 = DVG (320, 228)
  ONE_COIN_ONE_PLAY: {
    labs: { x: 0x50, y: 0x39 },
    glyphs: ['Char_1', 'Char_Space', 'Char_C', 'Char_O', 'Char_I', 'Char_N', 'Char_Space', 'Char_1', 'Char_Space', 'Char_P', 'Char_L', 'Char_A', 'Char_Y'],
  },
  // msg-id 10: "2_COINS_1_PLAY" — LABS (80, 57) ×4 = DVG (320, 228)
  TWO_COINS_ONE_PLAY: {
    labs: { x: 0x50, y: 0x39 },
    glyphs: ['Char_2', 'Char_Space', 'Char_C', 'Char_O', 'Char_I', 'Char_N', 'Char_S', 'Char_Space', 'Char_1', 'Char_Space', 'Char_P', 'Char_L', 'Char_A', 'Char_Y'],
  },
};

// Global scale used for all packed-message draws — set by $77F6
// at $77FD-$77FF (`LDA #$10; STA $00`).
export const PACKED_MSG_GS = 0x10;
